const DEFAULT_LANGUAGE_ID = '00000000-0000-0000-0000-000000000000';
const CODE_SAMPLE_INFO_TABLE = 'CodeSampleInfo';
const ACTIVE_CODE_SAMPLE_INFO = 'active';
const ARCHIVED_CODE_SAMPLE_INFO = 'archived';
const ITEM_NOT_FOUND_ERROR_CODE = 100;
const LANGUAGE_VARIANT_NOT_FOUND_ERROR_CODE = 103;

module.exports = {
    DEFAULT_LANGUAGE_ID,
    CODE_SAMPLE_INFO_TABLE,
    ITEM_NOT_FOUND_ERROR_CODE,
    LANGUAGE_VARIANT_NOT_FOUND_ERROR_CODE,
    ACTIVE_CODE_SAMPLE_INFO,
    ARCHIVED_CODE_SAMPLE_INFO
};
